openapi: 3.0.0
info:
  title: ToDo List API
  description: API for managing ToDo tasks
  contact:
    name: Uzayisenga Amina
    email: aminauzayisenga@gmail.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
- url: /
paths:
  /tasks:
    get:
      summary: Get all tasks
      operationId: getTasks
      responses:
        "200":
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
                x-content-type: application/json
      x-swagger-router-controller: Default
    post:
      summary: Create a new task
      operationId: createTask
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
        required: true
      responses:
        "201":
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
      x-swagger-router-controller: Default
  /tasks/{taskId}:
    get:
      summary: Get a task by ID
      operationId: getTaskById
      parameters:
      - name: taskId
        in: path
        description: ID of the task to retrieve/update/delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
      x-swagger-router-controller: Default
    put:
      summary: Update a task by ID
      operationId: updateTaskById
      parameters:
      - name: taskId
        in: path
        description: ID of the task to retrieve/update/delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
        required: true
      responses:
        "200":
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
      x-swagger-router-controller: Default
    delete:
      summary: Delete a task by ID
      operationId: deleteTaskById
      parameters:
      - name: taskId
        in: path
        description: ID of the task to retrieve/update/delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: Task deleted successfully
      x-swagger-router-controller: Default
components:
  schemas:
    Task:
      required:
      - title
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
      example:
        description: description
        id: 0
        title: title
